spring.application.name=BetoneiraSuplementos
app.users.file=./data/users.json
app.orders.file=./data/orders.json
app.products.file=./data/products.json
app.admin.email=admin@betoneira.com
app.admin.password=123456
app.admin.name=Administrador
